services:
  api1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - smartpark_network
  api2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - smartpark_network
  nginx:
    image: nginx:latest
    container_name: smartpark_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - smartpark_network

networks:
  smartpark_network:
    driver: bridge
