services:
  nginx:
    image: nginx:latest
    container_name: smartpark_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
    depends_on:
      - api
      # - frontend
    networks:
      - smartpark_network
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=postgres_writer;Port=5432;Database=smartpark;Username=admin;Password=admin
      - REDIS_HOST=redis:6379
    # depends_on:
    #   - postgres_writer
    #   - redis
    networks:
      - smartpark_network

  # postgres_writer:
  #   image: postgres:15
  #   container_name: smartpark_postgres_writer
  #   environment:
  #     POSTGRES_DB: smartpark
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - smartpark_network

  # postgres_reader1:
  #   image: postgres:15
  #   container_name: smartpark_postgres_reader1
  #   environment:
  #     POSTGRES_DB: smartpark
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - smartpark_network

  # postgres_reader2:
  #   image: postgres:15
  #   container_name: smartpark_postgres_reader2
  #   environment:
  #     POSTGRES_DB: smartpark
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5434:5432"
  #   networks:
  #     - smartpark_network

  # postgres_reader3:
  #   image: postgres:15
  #   container_name: smartpark_postgres_reader3
  #   environment:
  #     POSTGRES_DB: smartpark
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5435:5432"
  #   networks:
  #     - smartpark_network

  # redis:
  #   image: redis:7
  #   container_name: smartpark_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - smartpark_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: smartpark_frontend
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - VITE_API_URL=https://api.smartpark.local
  #   depends_on:
  #     - api
  #   networks:
  #     - smartpark_network

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: smartpark_prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - smartpark_network

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: smartpark_grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   networks:
  #     - smartpark_network

networks:
  smartpark_network:
    driver: bridge
