services:
  smartpark.api:
    image: ${DOCKER_REGISTRY-}smartparkapi
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    depends_on:
      - mongo
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=SmartParkDb
  mongo:
    image: mongo:latest
    container_name: smartpark-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      
volumes:
  mongo_data: