global:
  scrape_interval: 15s # Coleta métricas a cada 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - smartpark_api:5000
          - smartpark_api:5001

  - job_name: 'postgres'
    static_configs:
      - targets:
          - smartpark_postgres_writer:5432
          - smartpark_postgres_reader1:5432
          - smartpark_postgres_reader2:5432
          - smartpark_postgres_reader3:5432

  - job_name: 'redis'
    static_configs:
      - targets:
          - smartpark_redis:6379

  - job_name: 'nginx'
    static_configs:
      - targets:
          - smartpark_nginx:80
          - smartpark_nginx:443
